# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_token',
            field=models.CharField(default='anon', max_length=64),
        ),
    ]
