# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('event_category', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user_token',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default='default category', on_delete=django.db.models.deletion.CASCADE, to='ingest.EventCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.EventUser'),
            preserve_default=False,
        ),
    ]
