# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_auto_20160709_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcategory',
            old_name='event_category',
            new_name='category',
        ),
    ]
